version: '3.4'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './shared/nginx/vhost.d:/etc/nginx/vhost.d'
      - './shared/nginx/certs:/etc/nginx/certs:ro'
    networks:
      proxy: null
      identityserverui:
        aliases:
          - sts.identity-server.local
          - admin.identity-server.local
          - admin-api.identity-server.local
    restart: always


  db:
    image: 'mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04'
    ports:
      - '7900:1433'
    container_name: skoruba-identityserver4-db
    volumes:
      - ./mydata/db/data:/var/opt/mssql/data
      - ./mydata/db/log:/var/opt/mssql/log
      - ./mydata/db/backup:/var/opt/mssql/backup
    env_file:
      - ./.docker/db.env
    networks:
      identityserverui: null


  skoruba.identityserver4.admin:
    image: 'registry.gitlab.com/magus-devlabs/identityserver4/admin'
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin/Dockerfile
    container_name: skoruba-identityserver4-admin
    env_file:
      - ./.docker/admin.env
    command: dotnet Skoruba.IdentityServer4.Admin.dll /seed
    depends_on:
      - db
      - skoruba.identityserver4.sts.identity
    volumes:
      - './mydata/admin/log:/app/log'
      - './shared/serilog.json:/app/serilog.json'
      - './shared/identitydata.json:/app/identitydata.json'
      - './shared/identityserverdata.json:/app/identityserverdata.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui: null


  skoruba.identityserver4.admin.api:
    image: 'registry.gitlab.com/magus-devlabs/identityserver4/admin-api'
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin.Api/Dockerfile
    container_name: skoruba-identityserver4-admin-api
    env_file:
      - ./.docker/admin-api.env
    volumes:
      - './mydata/admin-api/log:/app/log'
      - './shared/serilog.json:/app/serilog.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui: null


  skoruba.identityserver4.sts.identity:
    image: 'registry.gitlab.com/magus-devlabs/identityserver4/sts-identity'
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.STS.Identity/Dockerfile
    container_name: skoruba-identityserver4-sts-identity
    env_file:
      - ./.docker/sts-identity.env
    depends_on:
      - db
    volumes:
      - './mydata/sts/log:/app/log'
      - './shared/serilog.json:/app/serilog.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui:
        aliases:
          - sts.identity-server.local

networks:
  proxy:
    driver: bridge
  identityserverui:
    driver: bridge
